name: video_provider
description: This library enables you to extract mp4 videos from various video providers.
# version: 1.0.0
# homepage: https://github.com/StefanLobbenmeier/video_provider

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
